CREATE TABLE InputPerCategory (
	CategoryId INT NOT NULL,
	InputId INT NOT NULL,
	Length INT DEFAULT 0,
	FOREIGN KEY (CategoryId) REFERENCES Categories(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (InputId) REFERENCES Inputs(id) ON UPDATE CASCADE ON DELETE CASCADE,
	INDEX USING HASH (CategoryId),
	INDEX USING HASH (InputId)

);

